/* AULA 44 --> AUTO RELACIONAMENTO */

CREATE DATABASE AULA44 

USE AULA44

CREATE TABLE CURSOS (
    ID_CURSO INT PRIMARY KEY IDENTITY(1,1),
    NOME VARCHAR(30),
    HORAS INT,
    VALOR DECIMAL(10,2),
    ID_PRE_REQ INT
)

ALTER TABLE CURSOS
ADD CONSTRAINT FK_PRE_REQ
FOREIGN KEY (ID_PRE_REQ)
REFERENCES CURSOS(ID_CURSO)

INSERT INTO CURSOS VALUES('BD RELACIONAL',20,400.00,NULL);
INSERT INTO CURSOS VALUES('BUSINESS INTELLIGENCE',40,800.00,1);
INSERT INTO CURSOS VALUES('RELATORIOS AVANCADOS',20,600.00,2);
INSERT INTO CURSOS VALUES('LOGICA PROGRAM',20,400.00,NULL);
INSERT INTO CURSOS VALUES('RUBY',30,500.00,4);

SELECT C.NOME , C.HORAS , C.VALOR, ISNULL(CAST(C.ID_PRE_REQ AS varchar), 'SEM REQUISITO') AS REQUISITO
FROM CURSOS C

/* DESAFIO NOME, VALOR, HORAS E O NOME DO PRE REQUISITO DO CURSO */

SELECT C.NOME AS CURSO,
       C.HORAS AS HORAS,
       C.VALOR AS VALOR,
       ISNULL(P.NOME,'------') AS 'PRÉ-REQUISITO'
       FROM CURSOS C
    LEFT JOIN CURSOS P ON P.ID_PRE_REQ = C.ID_CURSO -- USANDO O LEFT JOIN PARA TRAZER TODOS OS CURSOS MESMO QUE NÃO TENHAM PRÉ REQUISITO

------------------------------------------------------------------------------------

/* AULA 45 CURSORES */


CREATE DATABASE CURSORES;
USE CURSORES;

CREATE TABLE VENDEDORES(
	IDVENDEDOR INT PRIMARY KEY IDENTITY(1,1),
	NOME VARCHAR(50),
	JAN INT,
	FEV INT,
	MAR INT
);

INSERT INTO VENDEDORES VALUES('MAFRA',32432,242334,574545);
INSERT INTO VENDEDORES VALUES('CLARA',65465,65443,653454);
INSERT INTO VENDEDORES VALUES('JOAO',12432,65356,8756);
INSERT INTO VENDEDORES VALUES('LILIAN',4567,9676,8765);
INSERT INTO VENDEDORES VALUES('ANTONIO',3467,68756,99765);
INSERT INTO VENDEDORES VALUES('GLORIA',54786,76889,7098);

SELECT * FROM VENDEDORES;

SELECT NOME, (JAN+FEV+MAR) AS TOTAL FROM VENDEDORES;
SELECT NOME, (JAN+FEV+MAR) AS TOTAL, (JAN+FEV+MAR)/3 AS MEDIA FROM VENDEDORES;
GO

CREATE TABLE VEND_TOTAL(
	NOME VARCHAR(50),
	JAN INT,
	FEV INT,
	MAR INT,
	TOTAL INT,
	MEDIA INT
);

GO
CREATE PROCEDURE INSEREDADOS
AS
BEGIN
    -- Declaração de variáveis
    DECLARE @FIM BIT = 0;
    DECLARE @VAR1 INT, @VAR2 INT, @VAR3 INT, @VTOTAL INT, @VMEDIA INT;
    DECLARE @VNOME VARCHAR(50);

    -- Declaração do cursor
    DECLARE REG CURSOR FOR
        SELECT NOME, JAN, FEV, MAR 
        FROM VENDEDORES;

    -- Abertura do cursor
    OPEN REG;

    -- Loop para processar os dados
    FETCH NEXT FROM REG INTO @VNOME, @VAR1, @VAR2, @VAR3;

    WHILE @@FETCH_STATUS = 0
    BEGIN
        -- Cálculo de total e média
        SET @VTOTAL = @VAR1 + @VAR2 + @VAR3;
        SET @VMEDIA = @VTOTAL / 3;

        -- Inserção na tabela de totais
        INSERT INTO VEND_TOTAL (NOME, JAN, FEV, MAR, TOTAL, MEDIA)
        VALUES (@VNOME, @VAR1, @VAR2, @VAR3, @VTOTAL, @VMEDIA);

        -- Buscar o próximo registro
        FETCH NEXT FROM REG INTO @VNOME, @VAR1, @VAR2, @VAR3;
    END;

    -- Fechamento do cursor
    CLOSE REG;
    DEALLOCATE REG;
END;
GO

EXEC INSEREDADOS

SELECT * FROM VENDEDORES

SELECT * FROM VEND_TOTAL


-----------------------------------------------------------------

/* A47 SEGUNDA E TERCEIRAS FORMAS NORMAIS */

/*
	 PRIMEIRA FN
	 
	 ATOMICIDADE - UM CAMPO NAO PODE SER DIVISIVEL
	 UM CAMPO NAO PODE SER VETORIZADO
	 PK CHAVE PRIMARIA

*/

CREATE DATABASE CONSULTORIO;

USE CONSULTORIO

CREATE TABLE PACIENTE(
	ID_PACIENTE INT PRIMARY KEY IDENTITY(1,1),
	NOME VARCHAR(30),
	SEXO CHAR(1),
	EMAIL VARCHAR(30),
	NASCIMENTO DATE
);

CREATE TABLE MEDICO(
	ID_MEDICO INT PRIMARY KEY IDENTITY(1,1),
	NOME VARCHAR(30),
	SEXO CHAR(1),
	ESPECIALIDADE VARCHAR(30),
	FUNCIONARIO CHAR(1) 
);

CREATE TABLE HOSPITAL(
	ID_HOSPITAL INT PRIMARY KEY IDENTITY(1,1),
	NOME VARCHAR(30),
	BAIRRO VARCHAR(30),
	CIDADE VARCHAR(30),
	ESTADO CHAR(2)
);

CREATE TABLE CONSULTA(
	ID_CONSULTA INT PRIMARY KEY IDENTITY(1,1),
	ID_PACIENTE INT,
	ID_MEDICO INT,
	ID_HOSPITAL INT,
	DATA DATETIME,
	DIAGNOSTICO VARCHAR(50)
);

CREATE TABLE INTERNACAO(
	ID_INTERNACAO INT PRIMARY KEY IDENTITY(1,1),
	ENTRADA DATETIME,
	QUARTO INT,
	SAIDA DATETIME,
	OBSERVACOES VARCHAR(50),
	ID_CONSULTA INT 	
);  

/* CRIANDO AS CONSTRAINTS - OBJ (PK, FK) _ TABELA PERTENCENTE _ TABELA DE ONDE VEM*/

ALTER TABLE CONSULTA
ADD CONSTRAINT FK_CONSULTA_PACIENTE
FOREIGN KEY (ID_PACIENTE)
REFERENCES PACIENTE(ID_PACIENTE)

ALTER TABLE CONSULTA 
ADD CONSTRAINT FK_CONSULTA_MEDICO
FOREIGN KEY (ID_MEDICO)
REFERENCES MEDICO(ID_MEDICO)

ALTER TABLE CONSULTA
ADD CONSTRAINT FK_CONSULTA_HOSPITAL
FOREIGN KEY (ID_HOSPITAL)
REFERENCES HOSPITAL(ID_HOSPITAL)

ALTER TABLE INTERNACAO
ADD CONSTRAINT FK_INTERNACAO_CONSULTA
FOREIGN KEY (ID_CONSULTA)
REFERENCES CONSULTA(ID_CONSULTA)



