CREATE DATABASE Comercio

USE Comercio

CREATE TABLE CLIENTE(
    ID_CLIENTE int not null PRIMARY Key,
    NOME VARCHAR(20) not null,
    SEXO VARCHAR(1) NOT null,
    EMAIL VARCHAR(50),
    CPF VARCHAR(15) UNIQUE
);


CREATE TABLE ENDERECO(
    ID_ENDERECO INT NOT NULL PRIMARY KEY,
    RUA VARCHAR(30) NOT NULL,
    BAIRRO VARCHAR(30) NOT NULL,
    CIDADE VARCHAR(30) NOT NULL,
    ESTADO CHAR(2) NOT NULL,
    ID_CLIENTE INT UNIQUE FOREIGN KEY REFERENCES CLIENTE(ID_CLIENTE) -- 1X1 Usar UNIQUE 
);

CREATE TABLE TELEFONE(
    ID_TELEFONE INT NOT NULL PRIMARY KEY,
    TIPO VARCHAR(3) NOT NULL,
    NUMERO VARCHAR(20) NOT NULL,
    ID_CLIENTE INT FOREIGN KEY REFERENCES CLIENTE(ID_CLIENTE)
);

INSERT INTO CLIENTE VALUES(1,'JOAO','M','JOAOA@IG.COM','76567587887');
INSERT INTO CLIENTE VALUES(2,'CARLOS','M','CARLOSA@IG.COM','5464553466');
INSERT INTO CLIENTE VALUES(3,'ANA','F','ANA@IG.COM','456545678');
INSERT INTO CLIENTE VALUES(4,'CLARA','F',NULL,'5687766856');
INSERT INTO CLIENTE VALUES(5,'JORGE','M','JORGE@IG.COM','8756547688');
INSERT INTO CLIENTE VALUES(6,'CELIA','M','JCELIA@IG.COM','5767876889');
INSERT INTO CLIENTE VALUES(7 , 'PAULA' , 'F' , null , '23126789')
INSERT INTO CLIENTE VALUES(8 , 'FLAVIO' , 'M' , 'FLAVIO@IG.COM' , '67213935')
INSERT INTO CLIENTE VALUES(9 , 'ANDRE' , 'M' , 'ANDRE@GMAIL.COM' , '120213')
INSERT INTO CLIENTE VALUES(10 , 'GIOVANNA' , 'F' , NULL , '1209393')
INSERT INTO CLIENTE VALUES(11, 'KARLA' , 'F' , 'KARLA@GMAIL.COM' , '1221323')
INSERT INTO CLIENTE VALUES(12 , 'DANIELE' , 'F' , 'DAN@GMAIL.COM' , '1129323')
INSERT INTO CLIENTE VALUES(13 , 'LORENA' , 'F' , NULL , '12309323')
INSERT INTO CLIENTE VALUES(14 , 'EDUARDO' , 'M' , NULL , '12872323')
INSERT INTO CLIENTE VALUES(15, 'ANTONIO' , 'F' , 'ANTONIO@GMAIL.COM' , '1298323')
INSERT INTO CLIENTE VALUES(16 , 'ANTONIO' , 'M' , 'ANTONIO@UOL.COM' , '1203223')
INSERT INTO CLIENTE VALUES(17 , 'ELAINE' , 'M' , 'ELAINE@GMAIL.COM' , '1209023')
INSERT INTO CLIENTE VALUES(18 , 'CARMEM' , 'M' , 'CARM@GMAIL.COM' , '120323')
INSERT INTO CLIENTE VALUES(19, 'ADRIANA' , 'F' , 'DRI@GMAIL.COM' , '1232423')
INSERT INTO CLIENTE VALUES(20, 'MARCOS' ,'M' , 'MARC@IG.COM' , '98723499')
INSERT INTO CLIENTE VALUES(21 , 'JOICE' , 'F' , 'JOICE@GMAIL.COM' , '12045623')


INSERT INTO ENDERECO VALUES(1,'RUA ANTONIO SA','CENTRO','B. HORIZONTE','MG',4);
INSERT INTO ENDERECO VALUES(2,'RUA CAPITAO HERMES','CENTRO','RIO DE JANEIRO','RJ',1);
INSERT INTO ENDERECO VALUES(3,'RUA PRES VARGAS','JARDINS','SAO PAULO','SP',3);
INSERT INTO ENDERECO VALUES(4,'RUA ALFANDEGA','ESTACIO','RIO DE JANEIRO','RJ',2);
INSERT INTO ENDERECO VALUES(5,'RUA DO OUVIDOR','FLAMENGO','RIO DE JANEIRO','RJ',6);
INSERT INTO ENDERECO VALUES(6,'RUA URUGUAIANA','CENTRO','VITORIA','ES',5);
INSERT INTO ENDERECO VALUES(7 , 'JARDIM MIRRIAM' , 'SERRARIA' , 'DIADEMA' , 'SP' , 7)
INSERT INTO ENDERECO VALUES(8,'RUA GUEDES','CASCADURA','B. HORIZONTE','MG',9);
INSERT INTO ENDERECO VALUES(9,'RUA MAIA LACERDA','ESTACIO','RIO DE JANEIRO','RJ',10);
INSERT INTO ENDERECO VALUES(10,'RUA VISCONDESSA','CENTRO','RIO DE JANEIRO','RJ',11);
INSERT INTO ENDERECO VALUES(11,'RUA NELSON MANDELA','COPACABANA','RIO DE JANEIRO','RJ',12);
INSERT INTO ENDERECO VALUES(12,'RUA ARAUJO LIMA','CENTRO','VITORIA','ES',13);
INSERT INTO ENDERECO VALUES(13,'RUA CASTRO ALVES','LEBLON','RIO DE JANEIRO','RJ',14);
INSERT INTO ENDERECO VALUES(14,'AV CAPITAO ANTUNES','CENTRO','CURITIBA','PR',15);
INSERT INTO ENDERECO VALUES(15,'AV CARLOS BARROSO','JARDINS','SAO PAULO','SP',16);
INSERT INTO ENDERECO VALUES(16,'ALAMEDA SAMPAIO','BOM RETIRO','CURITIBA','PR',17);
INSERT INTO ENDERECO VALUES(17,'RUA DA LAPA','LAPA','SAO PAULO','SP',18);
INSERT INTO ENDERECO VALUES(18,'RUA GERONIMO','CENTRO','RIO DE JANEIRO','RJ',19);
INSERT INTO ENDERECO VALUES(19,'RUA GOMES FREIRE','CENTRO','RIO DE JANEIRO','RJ',20);
INSERT INTO ENDERECO VALUES(20,'RUA GOMES FREIRE','CENTRO','RIO DE JANEIRO','RJ',21);
INSERT INTO ENDERECO VALUES(21,'RUA GOMES FREIRE','CENTRO','RIO DE JANEIRO','RJ',8);


INSERT INTO TELEFONE VALUES(1 , 'CEL' , '90876-1234' ,6 )
INSERT INTO TELEFONE VALUES(2 , 'RES' , '92312-8934' ,5 )
INSERT INTO TELEFONE VALUES(3 , 'COM' , '90562-5634' ,3 )
INSERT INTO TELEFONE VALUES(4 , 'CEL' , '99082-3434' ,3 )
INSERT INTO TELEFONE VALUES(5 , 'CEL' , '92354-2334' ,5 )
INSERT INTO TELEFONE VALUES(6 , 'RES' , '92875-4534' ,7 )
INSERT INTO TELEFONE VALUES(7 , 'CEL' , '92123-2534' ,1 )
INSERT INTO TELEFONE VALUES(8 , 'CEL' , '99082-1908' ,1 )
INSERT INTO TELEFONE VALUES(9,'RES','68976565',9);
INSERT INTO TELEFONE VALUES(10,'CEL','99656675',9);
INSERT INTO TELEFONE VALUES(11,'CEL','33567765',11);
INSERT INTO TELEFONE VALUES(12,'CEL','88668786',11);
INSERT INTO TELEFONE VALUES(13,'COM','55689654',11);
INSERT INTO TELEFONE VALUES(14,'COM','88687979',12);
INSERT INTO TELEFONE VALUES(15,'COM','88965676',13);
INSERT INTO TELEFONE VALUES(16,'CEL','89966809',15);
INSERT INTO TELEFONE VALUES(17,'COM','88679978',16);
INSERT INTO TELEFONE VALUES(18,'CEL','99655768',17);
INSERT INTO TELEFONE VALUES(19,'RES','89955665',18);
INSERT INTO TELEFONE VALUES(20,'RES','77455786',19);
INSERT INTO TELEFONE VALUES(21,'RES','89766554',19);
INSERT INTO TELEFONE VALUES(22,'RES','77755785',20);
INSERT INTO TELEFONE VALUES(23,'COM','44522578',20);


SELECT * from CLIENTE
SELECT * from ENDERECO
SELECT * FROM TELEFONE

-- PROJEÇÃO -> Tudo o que você quer ver na tela

-- SELEÇÃO -> É UM SUBCONJUNTO DO CONJUNTO TOTAL DE REGISTROS DE UMA TABELA

-- CLAÚSULA DE SELEÇÃO É O WHERE 

SELECT NOME , SEXO , EMAIL -- PROJEÇÃO
FROM CLIENTE -- ORIGEM 
WHERE SEXO = 'F' -- SELEÇÃO\FILTRO

SELECT TIPO , NUMERO -- PROJEÇÃO
FROM TELEFONE -- ORIGEM
WHERE TIPO = 'CEL' -- SELEÇÃO\FILTRO

-- JUNÇÃO -> JOIN

SELECT NOME , EMAIL , ID_CLIENTE
FROM CLIENTE;

SELECT ID_CLIENTE , BAIRRO , CIDADE 
FROM ENDERECO;

-- NOME , SEXO , BAIRRO , CIDADE
SELECT NOME , SEXO , BAIRRO , CIDADE -- PROJEÇÃO
    FROM CLIENTE C -- ORIGEM
    INNER JOIN ENDERECO E ON C.ID_CLIENTE = E.ID_CLIENTE -- JOIN ON ID_CLIENTE\JUNÇÃO
WHERE SEXO = 'F'; -- SELEÇÃO\FILTRO

-- NOME , SEXO , EMAIL, TIPO, NUMERO
SELECT NOME , SEXO , EMAIL , TIPO , NUMERO -- PROJEÇÃO
    FROM CLIENTE C -- ORIGEM
    INNER JOIN TELEFONE T ON C.ID_CLIENTE = T.ID_CLIENTE; -- JUNÇÃO

 
-- NOME , SEXO , BAIRRO, CIDADE, TIPO , NUMERO
SELECT NOME ,SEXO , BAIRRO , CIDADE, TIPO , NUMERO -- PROJEÇÃO
    FROM CLIENTE C -- ORIGEM 
    INNER JOIN ENDERECO E ON C.ID_CLIENTE = E.ID_CLIENTE -- JUNÇÃO COM TABELA ENDERECO 
    INNER JOIN TELEFONE T ON C.ID_CLIENTE = T.ID_CLIENTE; -- JUNÇÃO COM TABELA TELEFONE



-- DML --> DATA MANIPULATION LANGUAGE 

INSERT INTO CLIENTE VALUES(8,'Marcia','M','marcia@gmail.com','90987651')

-- VERIFICAR POR SELECT ANTES DE FAZER O UPDATE OU DELETE
SELECT * FROM CLIENTE 
WHERE ID_CLIENTE = 8

UPDATE CLIENTE 
SET SEXO ='F'
WHERE ID_CLIENTE = 8

INSERT INTO CLIENTE VALUES(9,'XXX','M','XXX', 'XXX')
SELECT * FROM CLIENTE
WHERE ID_CLIENTE = 9

DELETE FROM CLIENTE 
WHERE ID_CLIENTE = 9


-- DDL --> DATA DEFINTION LANGUAGE

CREATE TABLE PRODUTO(
    ID_PRODUTO INT NOT NULL PRIMARY KEY,
    NOME_PRODUTO VARCHAR(30)NOT NULL,
    PRECO DECIMAL(10,2),
    FRETE DECIMAL(10,2)
)

-- COMANDO ALTER TABLE

-- ALTERANDO DADOS DE COLUNAS
ALTER TABLE PRODUTO
DROP COLUMN PRECO

ALTER TABLE PRODUTO
ALTER COLUMN VALOR_UNITARIO INT

ALTER TABLE PRODUTO
ADD VALOR_UNITARIO INT NOT NULL;

ALTER TABLE PRODUTO
ADD PESO DECIMAL(10,2) NOT NULL;

-- EXERCICIOS DML RELATORIO GERAL DE TODOS OS CLIENTES (TELEFONE E ENDERECO)

SELECT * FROM CLIENTE
SELECT * FROM ENDERECO
SELECT * FROM TELEFONE

SELECT C.ID_CLIENTE , C.NOME , C.SEXO , C.EMAIL, C.CPF ,
       E.RUA, E.BAIRRO , E.CIDADE , E.ESTADO,
       T.TIPO , T.NUMERO
FROM CLIENTE C
INNER JOIN ENDERECO E ON C.ID_CLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T ON C.ID_CLIENTE = T.ID_CLIENTE

-- RELATORIO GERAL DE HOMENS 
SELECT C.ID_CLIENTE , C.NOME , C.SEXO , C.EMAIL, C.CPF ,
       E.RUA, E.BAIRRO , E.CIDADE , E.ESTADO,
       T.TIPO , T.NUMERO
FROM CLIENTE C
INNER JOIN ENDERECO E ON C.ID_CLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T ON E.ID_CLIENTE = T.ID_CLIENTE
WHERE C.SEXO = 'M'

-- ARRUMAR OS SEXOS QUE ESTÃO ERRADOS (ID 6 , 17, 18)
SELECT * FROM CLIENTE 
WHERE ID_CLIENTE IN (6,17,18)

UPDATE CLIENTE 
    SET SEXO = 'F'
WHERE ID_CLIENTE IN (6,17,18) -- USANDO IN 


-- RELATORIO GERAL DE MULHERES 

-- ARRUMAR SEXO DE ANTÔNIO ANTES DE FAZER RELATÓRIO
UPDATE CLIENTE 
SET SEXO = 'M'
WHERE ID_CLIENTE = 15

SELECT C.ID_CLIENTE , C.NOME , C.SEXO , C.EMAIL, C.CPF ,
       E.RUA, E.BAIRRO , E.CIDADE , E.ESTADO,
       T.TIPO , T.NUMERO
FROM CLIENTE C
INNER JOIN ENDERECO E ON C.ID_CLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T ON E.ID_CLIENTE = T.ID_CLIENTE
WHERE C.SEXO = 'F';

-- QUANTIDADE DE HOMENS E MULHERES

SELECT COUNT(*) AS QUANTIDADE
FROM CLIENTE C
GROUP BY C.SEXO;

-- IDS E EMAIL DAS MULHERES QUE MOREM NO CENTRO DO RIO DE JANEIRO E 
-- NAO TENHAM CELULAR 

SELECT C.ID_CLIENTE, C.EMAIL, C.NOME, C.SEXO, T.TIPO, E.BAIRRO, E.CIDADE
FROM CLIENTE C
INNER JOIN ENDERECO E
ON C.ID_CLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T
ON C.ID_CLIENTE = T.ID_CLIENTE
WHERE SEXO = 'F'
AND E.BAIRRO = 'CENTRO' AND CIDADE = 'RIO DE JANEIRO'
AND (T.TIPO = 'RES' OR T.TIPO = 'COM')

-- EXERCICIO SEM RESOLUÇÃO NO MOMENTO

/*PARA UMA CAMPANHA DE MARKETING, O SETOR SOLICITOU UM
RELATÓRIO COM O NOME, EMAIL E TELEFONE CELULAR 
DOS CLIENTES QUE MORAM NO ESTADO DO RIO DE JANEIRO 
VOCÊ TERÁ QUE PASSAR A QUERY PARA GERAR O RELATORIO PARA
O PROGRAMADOR */

SELECT C.NOME , C.EMAIL , T.NUMERO -- PROJEÇÃO
    FROM CLIENTE C -- ORIGEM --> COLOCAR SEMPRE TABELA COM MAIS LIGAÇÕES
INNER JOIN TELEFONE T ON C.ID_CLIENTE = T.ID_CLIENTE -- JUNÇÃO COM CONDIÇÃO --> COLOCAR SEMPRE CONDIÇÃO NA TABELA DE ORIGEM
INNER JOIN ENDERECO E ON C.ID_CLIENTE = E.ID_CLIENTE -- JUNÇÃO COM CONDIÇÃO
WHERE E.ESTADO = 'RJ' AND T.TIPO = 'CEL' -- FILTRO


/* PARA UMA CAMPANHA DE PRODUTOS DE BELEZA, O COMERCIAL SOLICITOU UM
RELATÓRIO COM O NOME, EMAIL E TELEFONE CELULAR 
 DAS MULHERES QUE MORAM NO ESTADO DE SÃO PAULO 
VOCÊ TERÁ QUE PASSAR A QUERY PARA GERAR O RELATORIO PARA
O PROGRAMADOR */

SELECT C.NOME , C.EMAIL, T.NUMERO AS CELULAR 
    FROM CLIENTE C 
INNER JOIN TELEFONE T ON C.ID_CLIENTE = T.ID_CLIENTE
INNER JOIN ENDERECO E ON C.ID_CLIENTE = E.ID_CLIENTE
WHERE SEXO = 'F' AND E.ESTADO = 'SP' AND C.EMAIL IS NOT NULL

-- CLIENTE , EMIAL , ESTADO

SELECT C.NOME ,
       C.EMAIL, 
       E.ESTADO, 
       T.NUMERO
FROM CLIENTE C 
INNER JOIN ENDERECO E ON C.ID_CLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T ON C.ID_CLIENTE = T.ID_CLIENTE

-- IFNULL() --> AZURE = ISNULL

SELECT C.NOME ,
       ISNULL(C.EMAIL,'EMAIL NÃO INFORMADO') AS EMAIL, 
       E.ESTADO, 
       T.NUMERO
FROM CLIENTE C 
INNER JOIN ENDERECO E ON C.ID_CLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T ON C.ID_CLIENTE = T.ID_CLIENTE

-- RELATÓRIO GERAL DO BANCO

SELECT C.NOME , C.CPF , C.EMAIL, C.SEXO ,
       E.BAIRRO , E.CIDADE, E.ESTADO, E.RUA,
       T.NUMERO , T.TIPO
FROM CLIENTE C
INNER JOIN ENDERECO E ON C.ID_CLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T ON C.ID_CLIENTE = T.ID_CLIENTE

GO

-- VIEW --> CRIA UMA QUERY NA MEMÓRIA DO BANCO
CREATE VIEW V_RELATORIO AS
SELECT C.NOME , 
       C.CPF , 
       ISNULL(C.EMAIL,'*********') AS EMAIL, 
       C.SEXO ,
       E.BAIRRO , 
       E.CIDADE, 
       E.ESTADO, 
       E.RUA,
       T.NUMERO , 
       T.TIPO
FROM CLIENTE C
INNER JOIN ENDERECO E ON C.ID_CLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T ON C.ID_CLIENTE = T.ID_CLIENTE;
GO

SELECT * FROM V_RELATORIO;

-- APAGANDO UMA VIEW
DROP VIEW V_RELATORIO
GO

-- DANDO SELECT DENTRO DE UMA VIEW
SELECT NOME , NUMERO , ESTADO
FROM V_RELATORIO
GO

-- OPERACOES DML COM VIEW 
-- OBS.: VIEW NÃO ACEITA OPERAÇÕES COMO DELETE E INSERT , SÓ ACEITA UPDATE

INSERT INTO V_RELATORIO VALUES(
'ANDREIA','F','ANDREIA@UOL.COM.BR','CEL','873547864','CENTRO','VITORIA','ES'
);

-- ERROR 1394 (HY000): Can not insert into join view 'comercio.v_relatorio' without fields list
-- ERROR 1395 (HY000): Can not delete from join view 'comercio.v_relatorio'

DELETE FROM V_RELATORIO WHERE NOME = 'JORGE';

/* É PERMITIDO FAZER UPDATES EM VIEWS COM JOIN */

UPDATE V_RELATORIO SET NOME = 'JOSE' WHERE NOME = 'JORGE';

CREATE TABLE JOGADORES(
	IDJOGADOR INT,
	NOME VARCHAR(30),
	ESTADO CHAR(2)
);

INSERT INTO JOGADORES VALUES(1,'GUERRERO','RS');
INSERT INTO JOGADORES VALUES(2,'GABIGOL','RJ');
INSERT INTO JOGADORES VALUES(3,'GANSO','RJ');
INSERT INTO JOGADORES VALUES(4,'NENÊ', 'RJ');
INSERT INTO JOGADORES VALUES(5,'LOVE','SP');

GO
CREATE VIEW V_JOGADORES AS
SELECT NOME, ESTADO
FROM JOGADORES;
GO

SELECT * FROM V_JOGADORES;

DELETE FROM V_JOGADORES
WHERE NOME = 'GUERRERO';

INSERT INTO V_JOGADORES VALUES('GUERRERO','RS');

SELECT * FROM JOGADORES -- JOGADOR COM ID NULL , NÃO É RECOMENDADO;

-- USANDO FILTROS EM VIEWS

SELECT * FROM V_RELATORIO
WHERE SEXO = 'F';

/* ORDER BY */

CREATE TABLE ALUNOS(
    NUMERO INT NOT NULL,
    NOME VARCHAR(30)
)

INSERT INTO ALUNOS VALUES(1,'JOAO');
INSERT INTO ALUNOS VALUES(1,'MARIA');
INSERT INTO ALUNOS VALUES(2,'ZOE');
INSERT INTO ALUNOS VALUES(2,'ANDRE');
INSERT INTO ALUNOS VALUES(3,'CLARA');
INSERT INTO ALUNOS VALUES(1,'CLARA');
INSERT INTO ALUNOS VALUES(4,'MAFRA');
INSERT INTO ALUNOS VALUES(5,'JANAINA');
INSERT INTO ALUNOS VALUES(1,'JANAINA');
INSERT INTO ALUNOS VALUES(3,'MARCELO');
INSERT INTO ALUNOS VALUES(4,'GIOVANI');
INSERT INTO ALUNOS VALUES(5,'ANTONIO');
INSERT INTO ALUNOS VALUES(6,'ANA');
INSERT INTO ALUNOS VALUES(6,'VIVIANE'); 

SELECT * FROM ALUNOS
ORDER BY NUMERO;

SELECT * FROM ALUNOS
ORDER BY 1; -- 1 = NUMERO

SELECT * FROM ALUNOS
ORDER BY 2; -- 2 = COLUNA

-- ORDENANDO POR MAIS DE UMA COLUNA


SELECT * FROM ALUNOS
ORDER BY NUMERO, NOME

-- MESCLANDO ORDER BY COM PROJEÇÃO
SELECT NOME FROM ALUNOS
ORDER BY 1,2; -- NÃO FUNCIONA

SELECT NOME FROM ALUNOS
ORDER BY NUMERO, NOME; -- FUNCIONA

-- CRESCENTE E DECRESCENTE ASC --> CRESCENTE , DESC --> DECRESCENTE

SELECT * FROM ALUNOS
ORDER BY 1,2;

SELECT *  FROM ALUNOS
ORDER BY 1 ASC; --> PADRÃO

SELECT * FROM ALUNOS
ORDER BY 1 DESC

SELECT * FROM ALUNOS
ORDER BY 1,2 DESC;

SELECT * FROM ALUNOS
ORDER BY 1 DESC ,2 DESC;

-- ORDENANDO COM JOINS
SELECT C.NOME , 
       C.CPF , 
       ISNULL(C.EMAIL,'*********') AS EMAIL, 
       C.SEXO ,
       E.BAIRRO , 
       E.CIDADE, 
       E.ESTADO, 
       E.RUA,
       T.NUMERO , 
       T.TIPO
FROM CLIENTE C
INNER JOIN ENDERECO E ON C.ID_CLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T ON C.ID_CLIENTE = T.ID_CLIENTE
ORDER BY 1; -- NOME

SELECT * FROM V_RELATORIO
ORDER BY 1;

GO

/* PROCEDURES */

-- CRIANDO UMA PROCEDURE
CREATE PROCEDURE NOME_EMPRESA
AS
    BEGIN 
    SELECT 'NOME DA EMPRESA' AS EMPRESA;
END

-- EXCLUINDO UMA PROCEDURE
DROP PROCEDURE NOME

-- EXECUTANDO UMA PROCEDURE
EXEC NOME_EMPRESA


GO
-- PROCEDURE COM PARAMETROS
CREATE PROCEDURE CONTA(@N1 INT, @N2 INT)
AS
BEGIN
    SELECT @N1 + @N2 AS SOMA
END;

EXEC CONTA 10,2
