CREATE DATABASE CURSOS 

CREATE TABLE CURSO (
    ID_CURSO INT IDENTITY(1,1) PRIMARY KEY, -- ID auto-incrementado
    NOME VARCHAR(40),
    HORAS INT,
    PRECO DECIMAL(10,2)
);

CREATE PROCEDURE CAD_CURSO (
    @P_NOME VARCHAR(40),
    @P_HORAS INT,
    @P_PRECO DECIMAL(10,2)
)
AS
BEGIN
    -- Inserção dos dados na tabela CURSO
    INSERT INTO CURSO (NOME, HORAS, PRECO)
    VALUES (@P_NOME, @P_HORAS, @P_PRECO);
END;



EXEC CAD_CURSO 'JAVA', 30, 450.00
EXEC CAD_CURSO 'BI SQL SERVER',20,3000.00
EXEC CAD_CURSO 'POWER BI',20,1000.00
EXEC CAD_CURSO 'TABLEAU',30,1200.00

GO

-- CRIANDO PROCEDURE COM SELECT
CREATE PROCEDURE SELEC_CURSO(@P_ID_CURSO INT
)
AS
BEGIN
        SELECT NOME, HORAS , PRECO FROM CURSO
        WHERE ID_CURSO = @P_ID_CURSO
END

DROP PROCEDURE SELEC_CURSO

EXEC SELEC_CURSO 2

GO 

CREATE TABLE VENDEDORES(
    ID_VENDEDOR INT IDENTITY(1,1) PRIMARY KEY,
    NOME VARCHAR(40),
    SEXO CHAR(1),
    JANEIRO DECIMAL(10,2),
    FEVEREIRO DECIMAL(10,2),
    MARCO DECIMAL(10,2)
)

INSERT INTO VENDEDORES (NOME, SEXO, JANEIRO, FEVEREIRO, MARCO) VALUES
('Carlos Silva', 'M', 12000.50, 15000.75, 13000.80),
('Ana Pereira', 'F', 14000.00, 16000.50, 17000.25),
('João Oliveira', 'M', 10000.20, 11000.30, 12000.40),
('Mariana Costa', 'F', 15000.60, 14000.70, 13000.90),
('Ricardo Santos', 'M', 17000.10, 18000.20, 19000.30),
('Fernanda Lima', 'F', 20000.00, 21000.50, 22000.75),
('Paulo Almeida', 'M', 9000.80, 9500.90, 9200.10),
('Juliana Rocha', 'F', 13000.40, 14000.60, 15000.70),
('Gustavo Neves', 'M', 11000.30, 12000.50, 13000.40),
('Patrícia Mendes', 'F', 12500.75, 13500.80, 14500.90),
('Rafael Moreira', 'M', 16000.00, 17000.10, 18000.20),
('Camila Rezende', 'F', 10500.50, 11500.60, 12500.70),
('Bruno Nascimento', 'M', 9800.40, 10200.50, 10800.60),
('Larissa Cunha', 'F', 11500.30, 12000.40, 12500.50),
('Thiago Martins', 'M', 14000.00, 15000.20, 16000.30),
('Aline Ribeiro', 'F', 13000.50, 13500.70, 14000.90),
('Daniel Souza', 'M', 10000.00, 10500.10, 11000.20),
('Renata Gomes', 'F', 15000.60, 16000.70, 17000.80),
('Leonardo Fernandes', 'M', 17000.00, 17500.20, 18000.30),
('Viviane Barros', 'F', 19000.50, 20000.60, 21000.70);

-- MAX --> TRAZ O MAIOR VALOR DE UMA COLUNA

SELECT MAX(FEVEREIRO) AS MAIOR_FEVEREIRO
FROM VENDEDORES

-- MIN --> TRAZ O VALOR MINIMO DE UMA COLUNA
SELECT MIN(FEVEREIRO) AS MAIOR_FEVEREIRO
FROM VENDEDORES

-- AVG --> TRAZ O VALOR MÉDIO DE UMA COLUNA
SELECT AVG(FEVEREIRO) AS MED_FEVEREIRO
FROM VENDEDORES

-- MIX DE FUNÇÕES
SELECT MAX(JANEIRO) AS MAX_JAN,
       MIN(JANEIRO) AS MIN_JAN,
       AVG(JANEIRO)AS AVG_JAN
FROM VENDEDORES

-- TRUNCATE = FORMAT --> FORMATAÇÃO DE CASAS DECIMAIS
SELECT MAX(JANEIRO) AS MAX_JAN,
       MIN(JANEIRO) AS MIN_JAN,
       FORMAT(AVG(JANEIRO),'N2')AS AVG_JAN
FROM VENDEDORES

-- SUM

SELECT SUM(JANEIRO) AS SOMA_JANEIRO,
       SUM(FEVEREIRO) AS SOMA_FEV,
       SUM(MARCO) AS SOMA_MAR
FROM VENDEDORES

-- SUM COM GRORP BY
SELECT SEXO, SUM(JANEIRO) AS SOMA_JANEIRO
FROM VENDEDORES
GROUP BY SEXO

---------------------------------------------------------------


 /* SUB QUERYS */


-- VENDEDOR QUE VENDEU MENOS EM MARÇO 

SELECT NOME, MARCO AS VALOR
FROM VENDEDORES
WHERE MARCO = (SELECT MIN(MARCO) FROM VENDEDORES)

-- VENDEDOR QUE VENDEU MAIS EM MARCO 

SELECT NOME , MARCO AS VALOR_MARCO
FROM VENDEDORES
WHERE MARCO = (SELECT MAX(MARCO) FROM VENDEDORES)

-- VALORES ACIMA DA MÉDIA DE FEVEREIRO

SELECT FORMAT(AVG(FEVEREIRO),'N2', 'PT-BR') FROM VENDEDORES

SELECT FEVEREIRO AS VALORES_ACIMA_MED
FROM VENDEDORES
WHERE FEVEREIRO > (SELECT AVG(FEVEREIRO) FROM VENDEDORES) -- INNER QUERY

-- OBS.: USAR SUBQUERYS ONDE SE PRECISA USAR FUNÇÕES DE AGREGAÇÕES E QUERY COMUM

--------------------------------------------------------------------------------

-- OPERAÇÕES EM LINHAS

-- ENCONTRANDO A MÉDIA TRIMESTRAL DE CADA VENDEDOR

SELECT NOME,
       JANEIRO,         
       FEVEREIRO,
       MARCO,
       (JANEIRO+FEVEREIRO+MARCO) AS TOTAL_TRIMESTRAL,
       FORMAT((JANEIRO+FEVEREIRO+MARCO)/3, 'N2','PT-BR') AS MEDIA_TRIMESTRE   
FROM VENDEDORES

-- APLICANDO UMA %

SELECT NOME,
       JANEIRO,
       FEVEREIRO,
       MARCO,
       (JANEIRO+FEVEREIRO+MARCO) AS TOTAL_TRIMESTRE,
       FORMAT((JANEIRO+FEVEREIRO+MARCO)/3, 'N2','PT-BR') AS MEDIA_TRIMESTRE ,  
       FORMAT((JANEIRO+FEVEREIRO+MARCO) * 0.25, 'N2', 'PT-BR') AS DESCONTO
FROM VENDEDORES

CREATE DATABASE OFICINA

USE OFICINA

CREATE TABLE CLIENTE(
    ID_CLIENTE INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    NOME VARCHAR(30),
    SEXO CHAR(1),
    ID_CARRO INT 
)

CREATE TABLE TELEFONE(
    ID_TELEFONE INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    TIPO VARCHAR(3),
    NUMERO VARCHAR(30),
    ID_CLIENTE INT NOT NULL 
)

CREATE TABLE CARRO(
    ID_CARRO INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    MODELO VARCHAR(20),
    PLACA VARCHAR(30),
    ID_MARCA INT
)

CREATE TABLE COR(
    ID_COR INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    COR VARCHAR(20)
)

CREATE TABLE MARCA(
    ID_MARCA INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    MARCA VARCHAR(30) 
)

CREATE TABLE CARRO_COR(
    ID_COR INT NOT NULL ,
    ID_CARRO INT NOT NULL, 
    PRIMARY KEY(ID_COR , ID_CARRO)
)



-- CONSTRAINTS --> DEFINFIR AS CHAVE ESTRANGEIRAS APÓS AS CRIAÇÕES DAS TABELAS

ALTER TABLE TELEFONE
ADD CONSTRAINT FK_TELEFONE_CLIENTE
FOREIGN KEY(ID_CLIENTE)
REFERENCES CLIENTE(ID_CLIENTE)

ALTER TABLE CLIENTE 
ADD CONSTRAINT FK_CLIENTE_CARRO
FOREIGN KEY (ID_CARRO)
REFERENCES CARRO(ID_CARRO)

ALTER TABLE CARRO 
ADD CONSTRAINT FK_CARRO_MARCA
FOREIGN KEY (ID_MARCA)
REFERENCES MARCA(ID_MARCA)

ALTER TABLE CARRO_COR
ADD CONSTRAINT FK_COR
FOREIGN KEY (ID_COR)
REFERENCES COR(ID_COR)

ALTER TABLE CARRO_COR
ADD CONSTRAINT FK_CARRO
FOREIGN KEY (ID_CARRO)
REFERENCES CARRO(ID_CARRO)

-- Inserindo dados na tabela MARCA
INSERT INTO MARCA (MARCA) VALUES ('Toyota');
INSERT INTO MARCA (MARCA) VALUES ('Ford');
INSERT INTO MARCA (MARCA) VALUES ('Volkswagen');
INSERT INTO MARCA (MARCA) VALUES ('Chevrolet');
INSERT INTO MARCA (MARCA) VALUES ('Honda');
INSERT INTO MARCA (MARCA) VALUES ('Nissan');
INSERT INTO MARCA (MARCA) VALUES ('Hyundai');
INSERT INTO MARCA (MARCA) VALUES ('BMW');
INSERT INTO MARCA (MARCA) VALUES ('Mercedes-Benz');
INSERT INTO MARCA (MARCA) VALUES ('Audi');

-- Inserindo dados na tabela COR
INSERT INTO COR (COR) VALUES ('Preto');
INSERT INTO COR (COR) VALUES ('Branco');
INSERT INTO COR (COR) VALUES ('Prata');
INSERT INTO COR (COR) VALUES ('Azul');
INSERT INTO COR (COR) VALUES ('Vermelho');
INSERT INTO COR (COR) VALUES ('Amarelo');
INSERT INTO COR (COR) VALUES ('Cinza');
INSERT INTO COR (COR) VALUES ('Verde');
INSERT INTO COR (COR) VALUES ('Laranja');
INSERT INTO COR (COR) VALUES ('Rosa');

-- Inserindo dados na tabela CARRO
INSERT INTO CARRO (MODELO, PLACA, ID_MARCA) VALUES ('Corolla', 'ABC-1234', 1);
INSERT INTO CARRO (MODELO, PLACA, ID_MARCA) VALUES ('F-150', 'XYZ-5678', 2);
INSERT INTO CARRO (MODELO, PLACA, ID_MARCA) VALUES ('Golf', 'QWE-3456', 3);
INSERT INTO CARRO (MODELO, PLACA, ID_MARCA) VALUES ('Onix', 'RTY-7890', 4);
INSERT INTO CARRO (MODELO, PLACA, ID_MARCA) VALUES ('Civic', 'JKL-2345', 5);
INSERT INTO CARRO (MODELO, PLACA, ID_MARCA) VALUES ('Versa', 'LMN-5678', 6);
INSERT INTO CARRO (MODELO, PLACA, ID_MARCA) VALUES ('Elantra', 'TGH-1234', 7);
INSERT INTO CARRO (MODELO, PLACA, ID_MARCA) VALUES ('X5', 'QWE-6789', 8);
INSERT INTO CARRO (MODELO, PLACA, ID_MARCA) VALUES ('A-Class', 'ERT-4321', 9);
INSERT INTO CARRO (MODELO, PLACA, ID_MARCA) VALUES ('A3', 'YUI-5678', 10);

-- Inserindo dados na tabela CLIENTE
INSERT INTO CLIENTE (NOME, SEXO, ID_CARRO) VALUES ('João Silva', 'M', 1);
INSERT INTO CLIENTE (NOME, SEXO, ID_CARRO) VALUES ('Maria Souza', 'F', 2);
INSERT INTO CLIENTE (NOME, SEXO, ID_CARRO) VALUES ('Carlos Oliveira', 'M', 3);
INSERT INTO CLIENTE (NOME, SEXO, ID_CARRO) VALUES ('Fernanda Costa', 'F', 4);
INSERT INTO CLIENTE (NOME, SEXO, ID_CARRO) VALUES ('Pedro Santos', 'M', 5);
INSERT INTO CLIENTE (NOME, SEXO, ID_CARRO) VALUES ('Lucas Pereira', 'M', 6);
INSERT INTO CLIENTE (NOME, SEXO, ID_CARRO) VALUES ('Julia Almeida', 'F', 7);
INSERT INTO CLIENTE (NOME, SEXO, ID_CARRO) VALUES ('Ricardo Martins', 'M', 8);
INSERT INTO CLIENTE (NOME, SEXO, ID_CARRO) VALUES ('Camila Lima', 'F', 9);
INSERT INTO CLIENTE (NOME, SEXO, ID_CARRO) VALUES ('Gabriel Rocha', 'M', 10);

-- Inserindo dados na tabela TELEFONE
INSERT INTO TELEFONE (TIPO, NUMERO, ID_CLIENTE) VALUES ('CEL', '99999-1234', 11);
INSERT INTO TELEFONE (TIPO, NUMERO, ID_CLIENTE) VALUES ('CEL', '2345-6789', 12);
INSERT INTO TELEFONE (TIPO, NUMERO, ID_CLIENTE) VALUES ('CEL', '98888-5678', 14);
INSERT INTO TELEFONE (TIPO, NUMERO, ID_CLIENTE) VALUES ('CEL', '1234-4321', 14);
INSERT INTO TELEFONE (TIPO, NUMERO, ID_CLIENTE) VALUES ('CEL', '97777-8765', 15);
INSERT INTO TELEFONE (TIPO, NUMERO, ID_CLIENTE) VALUES ('CEL', '99222-3344', 16);
INSERT INTO TELEFONE (TIPO, NUMERO, ID_CLIENTE) VALUES ('CEL', '3333-5555', 17);
INSERT INTO TELEFONE (TIPO, NUMERO, ID_CLIENTE) VALUES ('CEL', '98877-6655', 18);
INSERT INTO TELEFONE (TIPO, NUMERO, ID_CLIENTE) VALUES ('CEL', '5555-9876', 19);
INSERT INTO TELEFONE (TIPO, NUMERO, ID_CLIENTE) VALUES ('CEL', '99999-1122', 20);

-- Inserindo dados na tabela CARRO_COR
INSERT INTO CARRO_COR (ID_COR, ID_CARRO) VALUES (1, 1);  -- Preto para o Corolla
INSERT INTO CARRO_COR (ID_COR, ID_CARRO) VALUES (2, 2);  -- Branco para o F-150
INSERT INTO CARRO_COR (ID_COR, ID_CARRO) VALUES (3, 3);  -- Prata para o Golf
INSERT INTO CARRO_COR (ID_COR, ID_CARRO) VALUES (4, 4);  -- Azul para o Onix
INSERT INTO CARRO_COR (ID_COR, ID_CARRO) VALUES (5, 5);  -- Vermelho para o Civic
INSERT INTO CARRO_COR (ID_COR, ID_CARRO) VALUES (6, 6);  -- Amarelo para o Versa
INSERT INTO CARRO_COR (ID_COR, ID_CARRO) VALUES (7, 7);  -- Cinza para o Elantra
INSERT INTO CARRO_COR (ID_COR, ID_CARRO) VALUES (8, 8);  -- Verde para o X5
INSERT INTO CARRO_COR (ID_COR, ID_CARRO) VALUES (9, 9);  -- Laranja para o A-Class
INSERT INTO CARRO_COR (ID_COR, ID_CARRO) VALUES (10, 10); -- Rosa para o A3

SELECT * FROM CLIENTE
SELECT * FROM TELEFONE
SELECT * FROM CARRO
SELECT * FROM COR
SELECT * FROM CARRO_COR
SELECT * FROM TELEFONE

----------------------------------------------------------------------------------

/* TRIGGER 

CREATE TRIGGER nome_da_trigger
ON nome_da_tabela
{ 
    AFTER | INSTEAD OF } 
    { INSERT | UPDATE | DELETE }
AS
BEGIN
    -- Código da trigger
END;

*/

-- ESTRUTURA DE UMA TRIGGER AULA 40

CREATE DATABASE AULA40

USE AULA40

CREATE TABLE USUARIO(
	ID_USUARIO INT PRIMARY KEY IDENTITY(1,1),
	NOME VARCHAR(30),
	LOGIN VARCHAR(30),
	SENHA VARCHAR(100)
);

CREATE TABLE BKP_USUARIO(
	ID_BACKUP INT PRIMARY KEY IDENTITY(1,1),
	ID_USUARIO INT,
	NOME VARCHAR(30),
	LOGIN VARCHAR(30)
);

-- TRIGGER PARA ADICIONAR OS USUARIOS DELETADOS EM UMA TABELA
CREATE TRIGGER BACKUP_USER
ON USUARIO
AFTER DELETE
AS
BEGIN
    -- Inserindo os dados deletados na tabela BKP_USUARIO
    INSERT INTO BKP_USUARIO (ID_USUARIO, NOME, LOGIN)
    SELECT ID_USUARIO, NOME, LOGIN
    FROM deleted;
END;

INSERT INTO USUARIO VALUES('ANDRE','ANDRE@GMAIL.COM','BOIABOIA123')

SELECT * FROM USUARIO

DELETE FROM USUARIO
WHERE ID_USUARIO = 1

SELECT * FROM BKP_USUARIO

GO

/* A 41 - COMUNICACAO ENTRE BANCOS DE DADOS */

CREATE DATABASE LOJA

USE LOJA

CREATE TABLE PRODUTO(
	ID_PRODUTO INT PRIMARY KEY IDENTITY(1,1),
	NOME VARCHAR(30),
	VALOR DECIMAL(10,2)
)

CREATE DATABASE BACKUPP

USE BACKUPP

CREATE TABLE BKP_PRODUTO(
	ID_BKP INT PRIMARY KEY IDENTITY(1,1),
	ID_PRODUTO INT,
	NOME VARCHAR(30),
	VALOR DECIMAL(10,2)
);

ALTER TABLE BKP_PRODUTO
ADD CONSTRAINT FK_PRODUTO_BKP_PRODUTO
FOREIGN KEY (ID_PRODUTO)
REFERENCES PRODUTO(ID_PRODUTO)

INSERT INTO BACKUPP.DBO.BKP_PRODUTO VALUES (1000,'TESTE',0.0);

SELECT * FROM BACKUPP.DBO.BKP_PRODUTO

-- CRIANDO TRIGGER PARA INSERIR NAS DUAS TABELAS
CREATE TRIGGER BACKUP_PRODUTO
ON LOJA.DBO.PRODUTO
AFTER INSERT
AS 
BEGIN
            INSERT INTO BACKUPP.DBO.BKP_PRODUTO (ID_PRODUTO , NOME , VALOR, EVENTO)
            SELECT ID_PRODUTO , NOME , VALOR, 'I'
            FROM INSERTED  
END;

DROP TRIGGER BACKUP_PRODUTO

ALTER TABLE PRODUTO
ADD EVENTO CHAR(1)

ALTER TABLE PRODUTO
DROP COLUMN EVENTO


INSERT INTO PRODUTO VALUES ('LIVRO SQL' , 120.00)
INSERT INTO PRODUTO VALUES ('LIVRO C#' , 80.00)
INSERT INTO PRODUTO VALUES ('LIVRO JAVA' , 60.00)
INSERT INTO PRODUTO VALUES ('LIVROC++' , 40.00)

-- CRIANDO TRIGGER PARA INSERIR QUANDO DELETAR DE UMA TABELA 
CREATE TRIGGER BACKUP_PRODUTO_DELETADO
ON LOJA.DBO.PRODUTO
AFTER DELETE
AS 
BEGIN
            INSERT INTO BACKUPP.DBO.BKP_PRODUTO (ID_PRODUTO , NOME , VALOR,EVENTO)
            SELECT ID_PRODUTO , NOME , VALOR, 'D'
            FROM DELETED
END;

DELETE FROM PRODUTO
WHERE ID_PRODUTO = 9

ALTER TABLE BACKUPP.DBO.BKP_PRODUTO
ADD EVENTO CHAR(1)

INSERT INTO PRODUTO VALUES ('LIVRO BI', 130.00)
DELETE FROM PRODUTO 
DELETE FROM BACKUPP.DBO.BKP_PRODUTO

SELECT * FROM PRODUTO
SELECT * FROM BACKUPP.DBO.BKP_PRODUTO

--------------------------------------------------------------

-- AULA 42 --> TRIGGER DE AUDITORIA

CREATE DATABASE LOJA2

USE LOJA2

CREATE TABLE PRODUTO(
	ID_PRODUTO INT PRIMARY KEY IDENTITY(1,1),
	NOME VARCHAR(30),
	VALOR DECIMAL(10,2)
)

INSERT INTO PRODUTO VALUES ('LIVRO SQL' , 120.00)
INSERT INTO PRODUTO VALUES ('LIVRO C#' , 80.00)
INSERT INTO PRODUTO VALUES ('LIVRO JAVA' , 60.00)
INSERT INTO PRODUTO VALUES ('LIVROC++' , 40.00)

CREATE DATABASE BACKUPP2

USE BACKUPP2

CREATE TABLE BKP_PRODUTO(
	ID_BKP INT PRIMARY KEY IDENTITY(1,1),
	ID_PRODUTO INT,
	NOME VARCHAR(30),
	VALOR_ORIGINAL DECIMAL(10,2),
    VALOR_ALTERADO DECIMAL(10,2),
    DATA DATETIME,
    USUARIO VARCHAR(30),
    EVENTO CHAR(1)
);


CREATE TRIGGER AUDIT_PROD
ON PRODUTO
AFTER UPDATE 
AS 
BEGIN
    INSERT INTO BACKUPP2.DBO.BKP_PRODUTO (ID_PRODUTO, NOME, VALOR_ORIGINAL, VALOR_ALTERADO, DATA, USUARIO, EVENTO)
    SELECT 
        D.ID_PRODUTO,
        D.NOME,
        D.VALOR AS VALOR_ORIGINAL,
        I.VALOR AS VALOR_ALTERADO,
        GETDATE(),
        SYSTEM_USER,
        'U'
    FROM DELETED D
    INNER JOIN INSERTED I
    ON D.ID_PRODUTO = I.ID_PRODUTO;
END;

UPDATE PRODUTO
SET VALOR = 130.00
WHERE ID_PRODUTO = 1

UPDATE PRODUTO
SET VALOR = 95.00
WHERE ID_PRODUTO = 2

SELECT * FROM BACKUPP2.DBO.BKP_PRODUTO
SELECT * FROM PRODUTO


