-- SEÇÃO 28 AULA 01

/* PROCEDURES */

--SP_ STORAGE PROCEDURE

USE EMPRESA
GO

CREATE TABLE PESSOA(
	ID_PESSOA INT PRIMARY KEY IDENTITY,
	NOME VARCHAR(30) NOT NULL,
	SEXO CHAR(1) NOT NULL CHECK (SEXO IN('M','F')), --ENUM
	NASCIMENTO DATE NOT NULL
)
GO


CREATE TABLE TELEFONE(
	ID_TELEFONE INT NOT NULL IDENTITY,
	TIPO CHAR(3) NOT NULL CHECK ( TIPO IN('CEL','COM')),
	NUMERO CHAR(10) NOT NULL,
	ID_PESSOA INT
)
GO

ALTER TABLE TELEFONE 
ADD CONSTRAINT FK_TELEFONE_PESSOA
FOREIGN KEY(ID_PESSOA) REFERENCES PESSOA(ID_PESSOA)
ON DELETE CASCADE
GO

DROP TABLE PESSOA

INSERT INTO PESSOA VALUES('ANTONIO','M','1981-02-13')
INSERT INTO PESSOA VALUES('DANIEL','M','1985-03-18')
INSERT INTO PESSOA VALUES('CLEIDE','F','1979-10-13')
INSERT INTO PESSOA VALUES('MAFRA','M','1981-02-13')

SELECT @@IDENTITY -- GUARDA O ULTIMO IDENTITY INSERIDO NA SEÇÃO
GO

SELECT * FROM PESSOA


INSERT INTO TELEFONE VALUES('CEL','9879008',1)
INSERT INTO TELEFONE VALUES('COM','8757909',1)
INSERT INTO TELEFONE VALUES('CEL','9875890',2)
INSERT INTO TELEFONE VALUES('CEL','9347689',2)
INSERT INTO TELEFONE VALUES('COM','2998689',3)
INSERT INTO TELEFONE VALUES('COM','2098978',2)
INSERT INTO TELEFONE VALUES('CEL','9008679',3)
GO

SELECT * FROM TELEFONE
GO

/* CRIANDO PROCEDURES */ 

CREATE PROC SOMA
AS
    SELECT 10 + 10 AS SOMA

GO

EXEC SOMA
GO

-- DINÂMICAS

CREATE PROC CONTA @NUM1 INT , @NUM2 INT
AS
    SELECT @NUM1 + @NUM2 AS RESULTADO
GO

EXEC CONTA 10 ,5
GO

/* PROCEDURES EM TABELAS */

SELECT P.NOME , T.NUMERO
FROM PESSOA P
INNER JOIN TELEFONE T ON T.ID_PESSOA = P.ID_PESSOA
WHERE TIPO = 'CEL'
GO

/* TRAZENDO NUMEROS DE ACORDO COM O TIPO PASSADO */

CREATE PROC TELEFONES @TIPO CHAR(3)
AS
        SELECT P.NOME , T.NUMERO
    FROM PESSOA P
    INNER JOIN TELEFONE T ON T.ID_PESSOA = P.ID_PESSOA
    WHERE TIPO = @TIPO
GO

EXEC TELEFONES 'CEL'
GO

EXEC TELEFONES 'COM'
GO

/* PARAMETROS DE OUTPUT */

SELECT TIPO , COUNT(*) AS QUANTIDADE
FROM TELEFONE
GROUP BY TIPO
GO

/* CRIANDO PROCEDURE COM PARÂMETROS DE ENTRADA E PARAMETRO DE SAIDA */

CREATE PROCEDURE GET_TIPO (@TIPO CHAR(3) , @RESULTADO INT OUTPUT)
AS  
        SELECT @RESULTADO = COUNT(*)
        FROM TELEFONE
        WHERE @TIPO = TIPO
GO

/* EXECUÇÃO DA PROC COM PARAMETRO DE SAÍDA */

/* TRANSACTION SQL -> LINGUAGEM QUE O SQL SERVER TRABALHA */

DECLARE @SAIDA INT
EXEC GET_TIPO @TIPO = 'CEL' , @RESULTADO = @SAIDA OUTPUT
SELECT @SAIDA
GO

-- MAIS SIMPLIFICADO 

DECLARE @SAIDA INT
EXEC GET_TIPO 'CEL' , @SAIDA OUTPUT
SELECT @SAIDA AS 'TIPO CEL'
GO

DECLARE @SAIDA INT
EXEC GET_TIPO 'COM' , @SAIDA OUTPUT
SELECT @SAIDA AS 'TIPO COM'
GO


/* PROCEDURE DE CADASTRO */


CREATE PROC CADASTRO (@NOME VARCHAR(30), @SEXO CHAR(1), @NASCIMENTO DATE,
@TIPO CHAR(3), @NUMERO VARCHAR(10))

AS
	DECLARE @FK INT

	INSERT INTO PESSOA VALUES(@NOME,@SEXO,@NASCIMENTO) -- GERAR UM ID_PESSOA PARA INSERIR NA TABELA TELEFONE

	SET @FK = (SELECT ID_PESSOA FROM PESSOA WHERE ID_PESSOA
	= @@IDENTITY) -- PEGA O ULTIMO ID INSERIDO

	INSERT INTO TELEFONE VALUES(@TIPO,@NUMERO,@FK)
GO

EXEC CADASTRO 'JORGE','M','1981-01-01','CEL','97273822'  
GO


SELECT P.ID_PESSOA,
       P.NOME, 
       P.SEXO , 
       P.NASCIMENTO,
       T.NUMERO,
       T.TIPO,
       T.ID_PESSOA
FROM PESSOA  P
INNER JOIN TELEFONE AS T
ON P.ID_PESSOA = T.ID_PESSOA;
GO

-- MANEIRA MAIS SIMPLES DE FAZER

/*
SELECT PESSOA.*, TELEFONE.*
FROM PESSOA
INNER JOIN TELEFONE
ON IDPESSOA = ID_PESSOA
GO
*/ 

----------------------------------------------------------

-- SEÇÃO 29 AULA 01 E 02

/* TSQL É UM BLOCO DE LINGUAGEM DE PROGRAMACAO.
PROGRAMAS SAO UNIDADES QUE PODEM SER CHAMADAS DE BLOCOS
ANÔNIMOS. BLOCOS ANONIMOS NAO RECEBEM NOME, POIS
NAO SAO SALVOS NO BANCO. CRIAMOS BLOCOS ANONIMOS QUANDO
IREMOS EXECUTA-LOS UMA SO VEZ OU TESTAR ALGO */

/* BLOCO DE EXECUÇÃO */ 

BEGIN 
        PRINT 'PRIMEIRO BLOCO'
END
GO


/* BLOCOS DE ATRIBUICAO DE VARIAVEIS */

DECLARE 
        @CONTADOR INT

BEGIN
        SET @CONTADOR = 5
        PRINT @CONTADOR
        SELECT @CONTADOR
END
GO

/* NO SQL SERVER CADA COLUNA, VARIÁVEL, LOCAL, EXPRESSAO E PARAMETRO TEM UM TIPO. */

DECLARE 
        @V_NUMERO NUMERIC(10,2) = 100.52,
        @V_DATA DATETIME = '20170207'
BEGIN
        PRINT 'VALOR NUMERICO: ' + CAST(@V_NUMERO AS VARCHAR)
        PRINT 'VALOR NUMERICO: ' + CONVERT(VARCHAR,@V_NUMERO)
        PRINT 'VALOR DE DATA: ' + CAST(@V_DATA AS VARCHAR)
        PRINT 'VALOR DE DATA: ' + CONVERT(VARCHAR, @V_DATA, 121) -- FORMATA A DATA NO PADRÃO EN-US
	PRINT 'VALOR DE DATA: ' + CONVERT(VARCHAR, @V_DATA, 120)
	PRINT 'VALOR DE DATA: ' + CONVERT(VARCHAR, @V_DATA, 105) -- FORMATA A DATA NO PADRÃO PT-BR
END 
GO

/* ATRIBUINDO RESULTADO A UMA VARÍAVEL */

CREATE TABLE CARROS(
    CARRO VARCHAR(20),
    FABRICANTE VARCHAR(30)
)
GO

INSERT INTO CARROS VALUES('KA','FORD')
INSERT INTO CARROS VALUES('FIESTA','FORD')
INSERT INTO CARROS VALUES('PRISMA','FORD')
INSERT INTO CARROS VALUES('CLIO','RENAULT')
INSERT INTO CARROS VALUES('SANDERO','RENAULT')
INSERT INTO CARROS VALUES('CHEVETE','CHEVROLET')
INSERT INTO CARROS VALUES('OMEGA','CHEVROLET')
INSERT INTO CARROS VALUES('PALIO','FIAT')
INSERT INTO CARROS VALUES('DOBLO','FIAT')
INSERT INTO CARROS VALUES('UNO','FIAT')
INSERT INTO CARROS VALUES('GOL','VOLKSWAGEN')
GO

DECLARE
        @V_CONT_FORD INT,
        @V_CONT_FIAT INT
BEGIN
        -- METODO 1 --> O SELECT PRECISA RETORNAR UMA SIMPLES COLUNA
        -- E UM RESULTADO

        SET @V_CONT_FORD = (SELECT COUNT(*) FROM CARROS WHERE FABRICANTE = 'FORD')
        PRINT 'QUANTIDADE FORD: ' + CAST(@V_CONT_FORD AS VARCHAR)

        -- METODO 2 
        SELECT @V_CONT_FIAT = COUNT(*) FROM CARROS WHERE FABRICANTE = 'FIAT'
        PRINT 'QUANTIDADE FIAT: ' + CONVERT(VARCHAR , @V_CONT_FIAT) 
END
GO

-- SEÇÃO 29 AULA 03

/* BLOCOS IF E ELSE 
BLOCO NOMEADO - PROCEDURES
*/

DECLARE
		@NUMERO INT = 6 --DINAMICO
BEGIN
		IF @NUMERO = 5 -- EXPRESSAO BOOLEANA - TRUE
			PRINT 'O VALOR É VERDADEIRO'
		ELSE
			PRINT 'O VALOR É FALSO'
END
GO

/* CASE */

DECLARE
		@CONTADOR INT
BEGIN
		SELECT -- O CASE REPRESENTA UMA COLUNA
		CASE
			WHEN FABRICANTE = 'FIAT' THEN 'FAIXA 1'
			WHEN FABRICANTE = 'CHEVROLET' THEN 'FAIXA 2'
			ELSE 'OUTRAS FAIXAS'
		END AS "INFORMACOES",
		*
		FROM CARROS
END
GO

SELECT -- O CASE REPRESENTA UMA COLUNA
	CASE
		WHEN FABRICANTE = 'FIAT' THEN 'FAIXA 1'
		WHEN FABRICANTE = 'CHEVROLET' THEN 'FAIXA 2'
		ELSE 'OUTRAS FAIXAS'
	END AS "INFORMACOES",
	*
FROM CARROS
GO

/* 
DECLARE
		@NUMERO INT = 6 --DINAMICO
BEGIN
		IF @NUMERO = 5 -- EXPRESSAO BOOLEANA - TRUE
			PRINT 'O VALOR É VERDADEIRO'
		ELSE
			PRINT 'O VALOR É FALSO'
END
GO

--> TRANSFORMANDO EM PROCEDURE
*/

-- EXERCICIO 

CREATE PROC VERIFICADOR (@NUM INT)
AS
        IF(@NUM = 5)
        BEGIN
                PRINT 'NUMERO VERDADEIRO'
        END        
        ELSE
            PRINT 'NUMERO FALSO'
GO

EXEC VERIFICADOR 3

-- SEÇÃO 29 AULA 04

DECLARE
            @I INT = 1
BEGIN
            WHILE(@I <= 15)
            BEGIN
                PRINT 'VALOR DE I: ' + CAST(@I AS VARCHAR)
            SET @I = @I + 1
            END 
END
GO

CREATE VIEW V_TESTE
AS
     SELECT * FROM CARROS
GO

SELECT GETDATE()
GO