-- SEÇÃO 26 AULA 1

CREATE DATABASE EMPRESA
GO

USE EMPRESA
GO  


/*CRIACAO DE TABELAS */

CREATE TABLE ALUNO(
	IDALUNO INT PRIMARY KEY IDENTITY,
	NOME VARCHAR(30) NOT NULL,
	SEXO CHAR(1) NOT NULL,
	NASCIMENTO DATE NOT NULL,
	EMAIL VARCHAR(30) UNIQUE
)
GO

/*CONSTRAINTS */

ALTER TABLE ALUNO
ADD CONSTRAINT CK_SEXO CHECK (SEXO IN('M','F'))
GO

/* 1 X 1 -- CHAVE ESTRANGEIRA SEMPRE NA TABELA MAIS FRACA */

CREATE TABLE ENDERECO(
	IDENDERECO INT PRIMARY KEY IDENTITY(100,10),
	BAIRRO VARCHAR(30),
	UF CHAR(2) NOT NULL
	CHECK (UF IN('RJ','SP','MG')), -- SIMULANDO UM ENUM 
	ID_ALUNO INT UNIQUE
)
GO

/* CRIANDO A FK */

ALTER TABLE ENDERECO ADD CONSTRAINT FK_ENDERECO_ALUNO
FOREIGN KEY(ID_ALUNO) REFERENCES ALUNO(IDALUNO)
GO

/* COMANDOS DE DESCRICAO */

/* PROCEDURES - JA CRIADAS E ARMAZENAS NO SISTEMA */

SP_COLUMNS ALUNO
GO

SP_HELP ALUNO
GO

/* INSERINDO DADOS */

INSERT INTO ALUNO VALUES('ANDRE','M','1981/12/09','ANDRE@IG.COM')
INSERT INTO ALUNO VALUES('ANA','F','1978/03/09','ANA@IG.COM')
INSERT INTO ALUNO VALUES('RUI','M','1951/07/09','RUI@IG.COM')
INSERT INTO ALUNO VALUES('JOAO','M','2002/11/09','JOAO@IG.COM')
GO

SELECT * FROM ALUNO
GO

/* ENDERECO */

INSERT INTO ENDERECO VALUES('FLAMENGO','RJ',1)
INSERT INTO ENDERECO VALUES('MORUMBI','SP',2)
INSERT INTO ENDERECO VALUES('CENTRO','MG',4)
INSERT INTO ENDERECO VALUES('CENTRO','SP',3)
GO

/* CRIANDO A TABELA TELEFONES 1 X N -- FK SEMPRE NA TABELA N  */
CREATE TABLE TELEFONE(
	IDTELEFONE INT PRIMARY KEY IDENTITY,
	TIPO CHAR(3) NOT NULL,
	NUMERO VARCHAR(10) NOT NULL,
	ID_ALUNO INT,
	CHECK (TIPO IN ('RES','COM','CEL'))
)
GO


INSERT INTO TELEFONE VALUES('CEL','7899889',1)
INSERT INTO TELEFONE VALUES('RES','4325444',1)
INSERT INTO TELEFONE VALUES('COM','4354354',2)
INSERT INTO TELEFONE VALUES('CEL','2344556',2)
GO

SELECT * FROM ALUNO
GO

SELECT * FROM ENDERECO
GO

SELECT * FROM TELEFONE
GO

---------------------------------------------------------------------

-- SEÇÃO 26 AULA 2

SELECT GETDATE()
GO

SELECT A.NOME , 
       ISNULL(T.TIPO,'------') AS TIPO, 
       ISNULL(T.NUMERO,'------') AS NUMERO, 
       A.SEXO,
       E.BAIRRO,
       E.UF
       FROM ALUNO A 
    INNER JOIN ENDERECO E ON E.ID_ALUNO = A.IDALUNO
    LEFT JOIN TELEFONE T ON T.ID_ALUNO = A.IDALUNO
GO

-- TRABALHANDO COM DATAS - CONTINUAÇÃO

SELECT NOME , NASCIMENTO
FROM ALUNO 
GO

-- GETDATE() TRAZ DIA E HORA ATUAL

SELECT NOME , GETDATE() AS DATA
FROM ALUNO
GO 

-- DATEDIFF ---> CALCULA A DIFERENÇA ENTRE 2 DATAS 

SELECT NOME , DATEDIFF(YEAR,NASCIMENTO,GETDATE()) AS ANOS_NASCIMENTO
FROM ALUNO 
GO

SELECT NOME , (DATEDIFF(DAY,NASCIMENTO,GETDATE())/365) AS DIAS_NASCIMENTO
FROM ALUNO
GO

SELECT NOME , (DATEDIFF(MONTH,NASCIMENTO,GETDATE())/12) AS MESES_NASCIMENTO
FROM ALUNO
GO

-- DATENAME --> TRAZ O NOME DA PARTE DA DATA EM QUESTÃO -- RETURN (STRING)

SELECT NOME , DATENAME(MONTH, NASCIMENTO)
FROM ALUNO
GO

SELECT NOME , DATENAME(WEEKDAY, NASCIMENTO)
FROM ALUNO
GO

-- DATEPART - DATENAME SÓ QUE RETORNA UM INTEIRO

SELECT NOME , DATEPART(MONTH, NASCIMENTO) AS MÊS, DATENAME(MONTH, NASCIMENTO) AS NOME_DO_MÊS
FROM ALUNO
GO

-- DATEADD --> RETORNA UMA DATA SOMADA A OUTRA

SELECT DATEADD(YEAR,10,GETDATE())

SELECT DATEADD(DAY,365,GETDATE())


-- SEÇÃO 26 AULA 04

-- CONVERSÃO DE DADOS 

SELECT 1 + '1'
GO

SELECT '1' + '1'
GO

SELECT 'CURSO DE BANCO DE DADOS ' + '1'
GO

SELECT 'CURSO DE BANCO DE DADOS' + 1
GO

/* EXERCICIO */

SELECT NOME , 
(CAST(DAY(NASCIMENTO) AS VARCHAR) + '/' + 
CAST(MONTH(NASCIMENTO) AS VARCHAR) + '/' + 
CAST(YEAR(NASCIMENTO) AS VARCHAR)) AS NASCIMENTO
FROM ALUNO
GO

-- SEÇÃO 26 AULA 06

/*CHARINDEX ---> RETORNA UM INTEIRO
CONTAGEM DEFAULT - INICIA EM 01
*/

SELECT NOME , CHARINDEX('A',NOME) AS INDICE 
FROM ALUNO
GO

-- PROCURA APARTIR DO INDICE 02
SELECT NOME , CHARINDEX('A',NOME,2) AS 'INDICE APARTIR DA 2ªP'
FROM ALUNO
GO

-- SEÇÃO 26 AULA 07

/* BULK INSERT - IMPORTAÇÃO DE ARQUIVOS */

CREATE TABLE LANCAMENTO_CONTABIL(
	CONTA INT,
	VALOR INT,
	DEB_CRED CHAR(1)
)
GO

SELECT * FROM LANCAMENTO_CONTABIL 
GO

-- \t --> TAB

BULK INSERT LANCAMENTO_CONTABIL
FROM 'CONTAS.txt'
WITH(
	FIRSTROW = 2,
	DATAFILETYPE = 'CHAR',
	FIELDTERMINATOR = '\t',
	ROWTERMINATOR = '\n'
)
GO

/* DESAFIO DO SALDO
QUERY QUE TRAGA O NUMERO DA CONTA 
SALDO - DEVEDOR OU CREDOR */

SELECT CONTA, VALOR, DEB_CRED,
CHARINDEX('D',DEB_CRED) AS DEBITO,
CHARINDEX('C',DEB_CRED) AS CREDITO,
CHARINDEX('C',DEB_CRED) * 2 - 1 AS MULTIPLICADOR
FROM LANCAMENTO_CONTABIL
GO

SELECT CONTA,
SUM(VALOR * (CHARINDEX('C',DEB_CRED) * 2 - 1)) AS SALDO
FROM LANCAMENTO_CONTABIL
GROUP BY CONTA
GO

--------------------------------------------------

-- SEÇÃO 27 AULA 01

USE EMPRESA
GO

CREATE TABLE PRODUTOS(
	ID_PRODUTO INT PRIMARY KEY IDENTITY,
	NOME VARCHAR(40),
	CATEGORIA VARCHAR(30),
	PRECO NUMERIC(10,2)
)
GO

CREATE TABLE HISTORICO(
	ID_HISTORICO INT PRIMARY KEY IDENTITY,
	PRODUTO VARCHAR(40),
	CATEGORIA VARCHAR(30),
	PRECO NUMERIC(10,2),
	PRECO_NOVO NUMERIC (10,2),
	DATA DATETIME,
	USUARIO VARCHAR(40),
	ACAO VARCHAR(100)
)
GO

INSERT INTO PRODUTOS VALUES('LIVRO SQL SERVER','LIVROS',98.00)
INSERT INTO PRODUTOS VALUES('LIVRO ORACLE','LIVROS',50.00)
INSERT INTO PRODUTOS VALUES('LICENÇA POWERCENTER','SOFTWARES',45000.00)
INSERT INTO PRODUTOS VALUES('NOTEBOOK I7','COMPUTADORES',3150.00)
INSERT INTO PRODUTOS VALUES('LIVRO BUSINESS INTELLIGENCE','LIVROS',90.00)
GO

CREATE TRIGGER TRG_ATUALIZA_PRECO
ON DBO.PRODUTOS
FOR UPDATE
AS
		DECLARE @ID_PRODUTO INT
		DECLARE @PRODUTO VARCHAR(40)
		DECLARE @CATEGORIA VARCHAR(30)
		DECLARE @PRECO NUMERIC(10,2)
		DECLARE @PRECO_NOVO NUMERIC(10,2)
		DECLARE @DATA DATETIME
		DECLARE @USUARIO VARCHAR(40)
		DECLARE @ACAO VARCHAR(100)

		-- PRIMEIRO BLOCO
		SELECT @ID_PRODUTO = ID_PRODUTO FROM inserted
		SELECT @PRODUTO = NOME FROM inserted
		SELECT @CATEGORIA = CATEGORIA FROM inserted 
		SELECT @PRECO = PRECO FROM deleted
		SELECT @PRECO_NOVO = PRECO FROM inserted

		-- SEGUNDO BLOCO
		SET @DATA = GETDATE()
		SET @USUARIO = USER_NAME()
		SET @ACAO = 'AÇÃO EXECUTADA PELA TRIGGER TRG_ATUALIZA_PRECO'

		INSERT INTO HISTORICO (PRODUTO, CATEGORIA, PRECO, PRECO_NOVO, DATA, USUARIO , ACAO)
		VALUES(@PRODUTO, @CATEGORIA, @PRECO, @PRECO_NOVO, @DATA, @USUARIO , @ACAO)

		PRINT 'AÇÃO EXECUTADA COM SUCESSO'

GO

DROP TRIGGER TRG_ATUALIZA_PRECO
GO

SELECT * FROM PRODUTOS
SELECT * FROM HISTORICO
GO

UPDATE PRODUTOS 
SET PRECO = 70.00
WHERE ID_PRODUTO = 2
GO

-- PROGRAMANDO TRIGGER PARA UMA COLUNA

CREATE TRIGGER TRG_ATUALIZA_PRECO
ON DBO.PRODUTOS
FOR UPDATE AS
IF UPDATE(PRECO)
BEGIN
		DECLARE @ID_PRODUTO INT
		DECLARE @PRODUTO VARCHAR(40)
		DECLARE @CATEGORIA VARCHAR(30)
		DECLARE @PRECO NUMERIC(10,2)
		DECLARE @PRECO_NOVO NUMERIC(10,2)
		DECLARE @DATA DATETIME
		DECLARE @USUARIO VARCHAR(40)
		DECLARE @ACAO VARCHAR(100)

		-- PRIMEIRO BLOCO
		SELECT @ID_PRODUTO = ID_PRODUTO FROM inserted
		SELECT @PRODUTO = NOME FROM inserted
		SELECT @CATEGORIA = CATEGORIA FROM inserted 
		SELECT @PRECO = PRECO FROM deleted
		SELECT @PRECO_NOVO = PRECO FROM inserted

		-- SEGUNDO BLOCO
		SET @DATA = GETDATE()
		SET @USUARIO = USER_NAME()
		SET @ACAO = 'AÇÃO EXECUTADA PELA TRIGGER TRG_ATUALIZA_PRECO'

		INSERT INTO HISTORICO (PRODUTO, CATEGORIA, PRECO, PRECO_NOVO, DATA, USUARIO , ACAO)
		VALUES(@PRODUTO, @CATEGORIA, @PRECO, @PRECO_NOVO, @DATA, @USUARIO , @ACAO)

		PRINT 'AÇÃO EXECUTADA COM SUCESSO'
END
GO

UPDATE PRODUTOS SET PRECO = 450.00
WHERE ID_PRODUTO = 2
GO

SELECT * FROM PRODUTOS
SELECT * FROM HISTORICO

UPDATE PRODUTOS SET NOME = 'LIVRO JAVA'
WHERE ID_PRODUTO = 2
GO

-- SEÇÃO 27 AULA 03

/* VARIAVEIS COM SELECT */

SELECT 10 + 10
GO

CREATE TABLE RESULTADO(
	IDRESULTADO INT PRIMARY KEY IDENTITY,
	RESULTADO INT
)
GO

INSERT INTO RESULTADO VALUES((SELECT 10 + 10))
GO

SELECT * FROM RESULTADO
GO

/* ATRIBUINDO SELECTS A VARIAVEIS - ANONIMO */

DECLARE
		@RESULTADO INT
		SET @RESULTADO = (SELECT 50 + 50)
		INSERT INTO RESULTADO VALUES(@RESULTADO)
GO
		


DECLARE
		@RESULTADO INT
		SET @RESULTADO = (SELECT 50 + 50)
		INSERT INTO RESULTADO VALUES(@RESULTADO)
		PRINT 'VALOR INSERIDO NA TABELA: ' + CAST(@RESULTADO AS VARCHAR)
GO
		

/* TRIGGER UPDATE */

CREATE TABLE EMPREGADO(
	ID_EMP INT PRIMARY KEY,
	NOME VARCHAR(30),
	SALARIO MONEY,
	ID_GERENTE INT
)
GO

ALTER TABLE EMPREGADO ADD CONSTRAINT FK_GERENTE
FOREIGN KEY(ID_GERENTE) REFERENCES EMPREGADO(ID_EMP)
GO


INSERT INTO EMPREGADO VALUES(1,'CLARA',5000.00,NULL)
INSERT INTO EMPREGADO VALUES(2,'CELIA',4000.00,1)
INSERT INTO EMPREGADO VALUES(3,'JOAO',4000.00,1)
GO

CREATE TABLE HIST_SALARIO(
	ID_EMPREGADO INT,
	ANTIGO_SAL MONEY,
	NOVO_SAL MONEY,
	DATA DATETIME
)
GO

CREATE TRIGGER TG_SALARIO
ON DBO.EMPREGADO
FOR UPDATE AS
IF UPDATE(SALARIO)
BEGIN
	 INSERT INTO HIST_SALARIO
	 (ID_EMPREGADO,ANTIGO_SAL,NOVO_SAL,DATA)
	 SELECT D.ID_EMP,D.SALARIO,I.SALARIO,GETDATE()
	 FROM DELETED D, inserted I
	 WHERE D.ID_EMP = I.ID_EMP
END
GO

UPDATE EMPREGADO SET SALARIO = SALARIO * 1.1
GO

SELECT * FROM EMPREGADO
GO

SELECT * FROM HIST_SALARIO
GO

/* SALARIO ANTIGO, NOVO, DATA E NOME DO EMPREGADO */

SELECT E.NOME, 
       HS.ANTIGO_SAL , 
	   HS.NOVO_SAL, 
	   HS.DATA
FROM EMPREGADO E
INNER JOIN HIST_SALARIO HS ON E.ID_EMP = HS.ID_EMPREGADO

USE EMPRESA

---------------------------------------------

-- SEÇÃO 27 AULA 04

-- TRIGGERS DE RANGE

CREATE TABLE SALARIO_RANGE(
	MAX_SAL MONEY,
	MIN_SAL MONEY
)
GO

INSERT INTO SALARIO_RANGE VALUES(9000.00,2000.00)
GO

CREATE TRIGGER TRG_SALARIO_RANGE
ON DBO.EMPREGADO
FOR INSERT,UPDATE
AS
		DECLARE
				@MAX_SAL MONEY,
				@MIN_SAL MONEY,
				@SALARIO_ATUAL MONEY
			
		SELECT @MAX_SAL = MAX_SAL, @MIN_SAL = MIN_SAL 
		FROM SALARIO_RANGE

		SELECT @SALARIO_ATUAL = I.SALARIO 
		FROM INSERTED I -- INSERTED PARA PEGAR O VALOR QUE SERÁ DIGITADA PELO USUÁRIO

	IF(@SALARIO_ATUAL > @MAX_SAL)
	BEGIN
			RAISERROR('VALOR MAIOR QUE O TETO SALARIAL', 16,1)
			ROLLBACK TRANSACTION
	END

	IF(@SALARIO_ATUAL < @MIN_SAL)
	BEGIN
			RAISERROR('VALOR MENOR QUE O PISO SALARIAL', 16,1)
			ROLLBACK TRANSACTION -- CANCELA O QUE FOI FEITO
	END
GO

UPDATE EMPREGADO 
SET SALARIO = 1000.00
WHERE ID_EMP = 1
GO

UPDATE EMPREGADO
SET SALARIO = 10000.00
WHERE ID_EMP = 1
GO

SELECT * FROM EMPREGADO
GO

SP_HELPTEXT TRG_SALARIO_RANGE
GO